local function Intents()
	local Table = {
		{Intent = 1, Toggle = true, Name = "Guilds"}, --0) Guilds (GUILD_CREATE, GUILD_UPDATE, GUILD_DELETE, GUILD_ROLE_CREATE, GUILD_ROLE_UPDATE, GUILD_ROLE_DELETE, CHANNEL_CREATE, CHANNEL_UPDATE, CHANNEL_DELETE, CHANNEL_PINS_UPDATE, THREAD_CREATE, THREAD_UPDATE, THREAD_DELETE, THREAD_LIST_SYNC, THREAD_MEMBER_UPDATE, THREAD_MEMBERS_UPDATE, STAGE_INSTANCE_CREATE, STAGE_INSTANCE_UPDATE, STAGE_INSTANCE_DELETE)
		{Intent = 2, Toggle = false, Name = "GUILD_MEMBERS"}, --1) GUILD_MEMBERS (GUILD_MEMBER_ADD, GUILD_MEMBER_UPDATE, GUILD_MEMBER_REMOVE, THREAD_MEMBERS_UPDATE) Privileged Intent
		{Intent = 4, Toggle = false, Name = "GUILD_MODERATION"}, --2) GUILD_MODERATION (GUILD_AUDIT_LOG_ENTRY_CREATE, GUILD_BAN_ADD, GUILD_BAN_REMOVE)
		{Intent = 8, Toggle = false, Name = "GUILD_EXPRESSIONS"}, --3) GUILD_EXPRESSIONS (GUILD_EMOJIS_UPDATE, GUILD_STICKERS_UPDATE, GUILD_SOUNDBOARD_SOUND_CREATE, GUILD_SOUNDBOARD_SOUND_UPDATE, GUILD_SOUNDBOARD_SOUND_DELETE, GUILD_SOUNDBOARD_SOUNDS_UPDATE)
		{Intent = 16, Toggle = false, Name = "GUILD_INTEGRATIONS"}, --4) GUILD_INTEGRATIONS (GUILD_INTEGRATIONS_UPDATE, INTEGRATION_CREATE, INTEGRATION_UPDATE, INTEGRATION_DELETE)
		{Intent = 32, Toggle = true, Name = "GUILD_WEBHOOKS"}, --5) GUILD_WEBHOOKS (WEBHOOKS_UPDATE)
		{Intent = 64, Toggle = false, Name = "GUILD_INVITES"}, --6) GUILD_INVITES (INVITE_CREATE, INVITE_DELETE)
		{Intent = 128, Toggle = false, Name = "GUILD_VOICE_STATES"}, --7) GUILD_VOICE_STATES (VOICE_CHANNEL_EFFECT_SEND, VOICE_STATE_UPDATE)
		{Intent = 256, Toggle = false, Name = "GUILD_PRESENCES"}, --8) GUILD_PRESENCES (PRESENCE_UPDATE) Privileged Intent
		{Intent = 512, Toggle = true, Name = "GUILD_MESSAGES"}, --9) GUILD_MESSAGES (MESSAGE_CREATE, MESSAGE_UPDATE, MESSAGE_DELETE, MESSAGE_DELETE_BULK)
		{Intent = 1024, Toggle = false, Name = "GUILD_MESSAGE_REACTIONS"}, --10) GUILD_MESSAGE_REACTIONS (MESSAGE_REACTION_ADD, MESSAGE_REACTION_REMOVE, MESSAGE_REACTION_REMOVE_ALL, MESSAGE_REACTION_REMOVE_EMOJI)
		{Intent = 2048, Toggle = false, Name = "GUILD_MESSAGE_TYPING"}, --11) GUILD_MESSAGE_TYPING (TYPING_START)
		{Intent = 4096, Toggle = false, Name = "DIRECT_MESSAGES"}, --12) DIRECT_MESSAGES (MESSAGE_CREATE, MESSAGE_UPDATE, MESSAGE_DELETE, CHANNEL_PINS_UPDATE)
		{Intent = 8192, Toggle = false, Name = "DIRECT_MESSAGE_REACTIONS"}, --13) DIRECT_MESSAGE_REACTIONS (MESSAGE_REACTION_ADD, MESSAGE_REACTION_REMOVE, MESSAGE_REACTION_REMOVE_ALL, MESSAGE_REACTION_REMOVE_EMOJI)
		{Intent = 16384, Toggle = false, Name = "DIRECT_MESSAGE_TYPING"}, --14) DIRECT_MESSAGE_TYPING (TYPING_START)
		{Intent = 32768, Toggle = true, Name = "MESSAGE_CONTENT"}, --15) MESSAGE_CONTENT () Privileged Intent
		{Intent = 65536, Toggle = false, Name = "GUILD_SCHEDULED_EVENTS"}, --16) GUILD_SCHEDULED_EVENTS (GUILD_SCHEDULED_EVENT_CREATE, GUILD_SCHEDULED_EVENT_UPDATE, GUILD_SCHEDULED_EVENT_DELETE, GUILD_SCHEDULED_EVENT_USER_ADD, GUILD_SCHEDULED_EVENT_USER_REMOVE)
		--{Intent = 131072, Toggle = false, Name = "UNUSED"}, --17) UNUSED
		--{Intent = 262144, Toggle = false, Name = "UNUSED"}, --18) UNUSED
		--{Intent = 524288, Toggle = false, Name = "UNUSED"}, --19) UNUSED
		{Intent = 1048576, Toggle = false, Name = "AUTO_MODERATION_CONFIGURATION"}, --20) AUTO_MODERATION_CONFIGURATION (AUTO_MODERATION_RULE_CREATE, AUTO_MODERATION_RULE_UPDATE, AUTO_MODERATION_RULE_DELETE)
		{Intent = 2097152, Toggle = false, Name = "AUTO_MODERATION_EXECUTION"}, --21) AUTO_MODERATION_EXECUTION (AUTO_MODERATION_ACTION_EXECUTION)
		--{Intent = 4194304, Toggle = false, Name = "UNUSED"}, --22) UNUSED
		--{Intent = 8388608, Toggle = false, Name = "UNUSED"}, --23) UNUSED
		{Intent = 16777216, Toggle = false, Name = "GUILD_MESSAGE_POLLS"}, --24) GUILD_MESSAGE_POLLS (MESSAGE_POLL_VOTE_ADD, MESSAGE_POLL_VOTE_REMOVE)
		{Intent = 33554432, Toggle = false, Name = "DIRECT_MESSAGE_POLLS"} --25) DIRECT_MESSAGE_POLLS (MESSAGE_POLL_VOTE_ADD, MESSAGE_POLL_VOTE_REMOVE)
	}
	local Integer = 0
	local String = "Enabled Intents: "
	for _, Data in pairs(Table) do
		if Data.Toggle then
			Integer = Integer + Data.Intent
			String = String .. Data.Name .. ", "
		end
	end
	Bot_Intent = Integer
	String = String:sub(1, String:len() - 2)
	Write(String)
	return Integer
end

return Intents